apiVersion: v1
metadata:
  name: Testcafe+Cucumber integration
files:
  - ./features/
suites:
  - name: "SauceDemo"
    match: features/SauceDemo.feature
  - name: "SauceDemoLogins"
    match: features/SauceDemoLogins.feature
  - name: "All Features"
    match: features/(.*)\.feature
image:
  base: stt-testcafe-cucumber-node
  version: latest
